<?php
/** @var \Zend\Form\Form $form */
$form = $this->form;
$form->setAttribute('method', 'post');
$form->setAttribute('id', 'entityform');
//echo $this->formCollection($form); exit;
$title = "Add Information";
echo $this->form()->openTag($form);
$this->headTitle($title);
?>

<h4>Information >> Add<span style="float:right;">
        <input class="btn btn-primary" type="submit" value="Save" />
        <a class="btn btn-default" href="<?php echo $this->url("admin-review"); ?>">Cancel</a></span></h4>
<hr>
<?php
if($this->flashMessenger()->hasCurrentErrorMessages()){
    foreach($this->flashMessenger()->getCurrentErrorMessages() as $msg){
        echo '<div class="alert alert-danger" role="alert">'.$msg.'</div>';
    }
}

?>
<?php
if($this->flashMessenger()->hasCurrentSuccessMessages()){
    foreach($this->flashMessenger()->getCurrentSuccessMessages() as $msg){
        echo '<div class="alert alert-success" role="alert">'.$msg.'</div>';
    }

}
$this->flashMessenger()->clearCurrentMessagesFromContainer();
?>
<?php
/** @var \Zend\Form\Element $element */
foreach($form->getElements() as $element ){
    if($element->getName() == "content"){
        $element->setAttribute('id', 'content');
    }

    $element->setLabel(preg_replace('/(?<!\ )[A-Z]/', ' $0', ucfirst($element->getName())));

    echo $this->formRow($element, null, false);
    if ($this->formElementerrors($element)) {
        echo '<div class="alert alert-danger" role="alert">' . $this->formElementerrors($element) . '</div>';
    }
}
?>

<?php
echo $this->form()->closeTag();
?>
<div>
    <strong>How to access Info page?</strong><br>
    <p><?php echo $this->settingHelper('site_url'); ?>/info/[INFORMATION_PAGE_ID]</p>
</div>
<style>
    #entityform label span, #entityform > input {
        display: block;

    }

    #entityform > label {
        width: 100%;
        font-weight: normal;
    }

    #entityform > label > input {
        width: 100%;
    }

    #entityform > label > input[type=radio] {
        width: auto;
        display: inline;
    }

    textarea {
        width: 100%;
    }

    .label-txt {
        padding: 0px 15px ;
    }
    .thumb-container{
        padding: 10px;
    }
    input[type=checkbox]{
        float: left;display: inline; width: auto !important;
    }

</style>
<?php
$this->headLink()->prependStylesheet($this->basePath() . '/js/fancybox/source/jquery.fancybox.css')
?>
<?php $this->headScript()
    ->prependFile($this->basePath() . '/js/tinymce/tinymce.min.js')
    ->prependFile($this->basePath() . '/js/fancybox/source/jquery.fancybox.js'); ?>
<script>
    $(document).ready(function(){
        tinymce.init({
            selector: "#content",
            theme: "modern",
            plugins: [
                "advlist autolink link image lists charmap print preview hr anchor pagebreak",
                "searchreplace wordcount visualblocks visualchars insertdatetime media code nonbreaking",
                "table contextmenu directionality emoticons paste textcolor responsivefilemanager"
            ],
            toolbar1: "undo redo | bold italic underline | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | styleselect",
            toolbar2: "| responsivefilemanager | link unlink anchor | image media | forecolor backcolor  | print preview code ",
            image_advtab: true,

            external_filemanager_path: "<?php echo $this->url("home"); ?>ResponsiveFilemanager/filemanager/",
            filemanager_title: "File Manager",
            external_plugins: { "filemanager": "<?php echo $this->url("home"); ?>ResponsiveFilemanager/filemanager/plugin.min.js"}
        });
    });

</script>