<?php
$this->headTitle("Dashboard");
?>
    <h4>Dashboard</h4>
    <hr>


    <div class="alert alert-info">

        You are logged in.

    </div>
<h4>Latest Orders</h4><hr>
<?php
if(count($this->orders) == 0){
    echo "There are no orders in the database.";
} else { ?>
<table class="table table-hover table-striped  table-responsive">

    <thead>

    <tr>

        <th>ID</th>

        <th>Order By</th>

        <th>DateTime</th>

        <th>Total Price</th>
        <th>Status</th>
        <th>Action</th>
    </tr>
    </thead>

    <tbody>
    <?php
    foreach ($this->orders as $k=>$entity) {

        ?>
        <tr>
            <td><?php echo $entity->getOrderId(); ?></td>

            <td>
                <?php
                echo $entity->getUser()->getFirstname()." ". $entity->getUser()->getLastname();

                ?>
            </td>
            <td><?php echo $entity->getOrderDatetime()->format('l, F d Y h:i A');; ?></td>

            <?php
            $total = 0;
            foreach($this->products[$k] as $product){
                $total += $product->getQuantity() * $product->getUnitPrice();
            }
            ?>

            <td><?php echo $this->settingHelper("currency_prefix") . number_format((float)($total), 2, '.', '') . $this->settingHelper("currency_postfix"); ?></td>
            <td><?php echo $this->settingHelper("order_status_".((int)$entity->getOstatus())); ?></td>
            <td><a href="<?php echo $this->url("admin-order", array('action' => 'edit',"id" => $entity->getOrderId())); ?>" class="btn btn-default">Edit</a></td>

        </tr>
    <?php
    }
    ?>
    </tbody>
</table>
<?php } ?>

    <h4>Latest Product Reviews</h4><hr>
<?php
if(count($this->reviews) == 0){
    echo "There are no product reviews in the database.";
} else { ?>
    <table class="table table-hover table-striped table-responsive">

            <thead>

            <tr>

                <th>ID</th>
                <th>Product</th>
                <th>Reviewer Name</th>

                <th>Stars</th>
                <th>Approved</th>
                <th>Action</th>
            </tr>
            </thead>

            <tbody>
            <?php
            foreach ($this->reviews as $entity) {

                ?>
                <tr>
                    <td><?php echo $entity->getProductReviewId(); ?></td>
                    <td><?php echo $entity->getProduct()->getTitle(); ?></td>

                    <td>
                        <?php
                        echo $entity->getReviewerName();

                        ?>
                    </td>

                    <td>
                        <?php
                        echo $entity->getStars();

                        ?>
                    </td>
                    <td>
                        <?php
                        echo $entity->getApproved() == 0? "No" : "Yes";

                        ?>
                    </td>

                    <td><a href="<?php echo $this->url("admin-review", array('action' => 'edit',"id" => $entity->getProductReviewId())); ?>" class="btn btn-default">Edit</a></td>

                </tr>
            <?php
            }
            ?>
            </tbody>
        </table>
<?php } ?>

