<?php
/**
 * Configuration file generated by ZFTool
 * The previous configuration file is stored in application.config.old
 *
 * @see https://github.com/zendframework/ZFTool
 */
return array(
    'modules' => array(
        'Application',
        'Admin\\AdminAuthentication',
        'Admin\\AdminAccount',
        'Admin\\Category',
        'Admin\\Product',
        'Admin\\User',
        'Admin\\Order',
        'Admin\\Setting',
        'DoctrineModule',
        'DoctrineORMModule',
        'Catalog',
        'Admin\\Staff',
        'Admin\\Review',
        'Admin\\Information',
        'Admin\\Newsletter',
        'Admin\\Colour',
        'Admin\\Options'
    ),
    'module_listener_options' => array(
        'module_paths' => array(
            './module',
            './vendor'
        ),
        'config_glob_paths' => array(
            'config/autoload/{,*.}{global,local}.php'
        )
    ),
    'view_helpers' => array(
        'invokables' => array(
            'settingHelper' => 'Catalog\\View\\Helper\\SettingHelper'
        )
    )
);
