<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->settingHelper("site_name"))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                        ->prependStylesheet($this->basePath() . '/js/jquery-ui-1.11.1/jquery-ui.min.css')
                        ->prependStylesheet($this->basePath() . '/js/datetimepicker/jquery.datetimepicker.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/admin-custom.js')

            ->prependFile($this->basePath() . '/js/datetimepicker/jquery.datetimepicker.js')
            ->prependFile($this->basePath() . '/js/jquery-ui-1.11.1/jquery-ui.min.js')
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>
<script>
    var js_setting = {
        images_dir: '<?php echo $this->settingHelper('images_dir'); ?>',
        thumbs_dir: '<?php echo $this->settingHelper('thumbs_dir'); ?>',
        site_url: '<?php echo $this->settingHelper('site_url'); ?>',
        currency_prefix: '<?php echo $this->settingHelper('currency_prefix'); ?>',
        currency_postfix: '<?php echo $this->settingHelper('currency_postfix'); ?>'
    };
</script>
    </head>
    <body>
    <?php $partial = array('partial/navigation/admin.phtml', 'default') ?>
    <?php $this->navigation('navigation')->menu()->setPartial($partial) ?>
    <?php echo $this->navigation('navigation')->menu()->render() ?>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p >&copy; <?php echo date('Y') ?> Mantissa Dress Co. <?php echo $this->translate('All rights reserved.') ?> Powered by Immense Systems</p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
