<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <?php echo $this->headTitle($this->settingHelper("site_name"))->setSeparator(' - ')->setAutoEscape(false) ?>
    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>
    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/catalog/plugins/jquery-notif/ui.notify.css')
        ->prependStylesheet($this->basePath() . '/catalog/plugins/PgwSlider/pgwslider.css')
        ->prependStylesheet($this->basePath() . '/catalog/plugins/fancybox/source/jquery.fancybox.css')
        ->prependStylesheet($this->basePath() . '/catalog/css/custom.css')
        ->prependStylesheet($this->basePath() . '/js/jquery-ui-1.11.1/jquery-ui.min.css')
        ->prependStylesheet($this->basePath() . '/catalog/plugins/bootstrap-3.2.0/css/bootstrap.css')
    ?>
    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath() . '/js/admin-custom.js')

        ->prependFile($this->basePath() . '/catalog/plugins/jquery-notif/src/jquery.notify.js')

        ->prependFile($this->basePath() . '/catalog/plugins/PgwSlider/pgwslider.js')
        ->prependFile($this->basePath() . '/catalog/plugins/fancybox/source/jquery.fancybox.js')
        ->prependFile($this->basePath() . '/catalog/js/custom.js')
        ->prependFile($this->basePath() . '/catalog/plugins/responsiveCarousel/responsiveCarousel.js')
        ->prependFile($this->basePath() . '/js/jquery-ui-1.11.1/jquery-ui.min.js')

        ->prependFile($this->basePath() . '/catalog/plugins/bootstrap-3.2.0/js/bootstrap.js')
        ->prependFile($this->basePath() . '/js/jquery.min.js')
    ; ?>


    <link href='http://fonts.googleapis.com/css?family=Abel' rel='stylesheet' type='text/css'>

</head>
<body>
<div class="container">
    <header class="row">
        <div class="text-center">
            <a href="<?php echo $this->url("admin"); ?>">
                <img class="logo" src="<?php echo $this->basePath('img/logo.jpg') ?>" alt="Mantissa Dress Co."/>
            </a>

        </div>
    </header>



    <?php echo $this->content; ?>

    <hr>

    <div class="row text-center">
        <p>&copy Mantissa Dress Co. 2014 - All rights reserved</p>
    </div>
</div>


<!-- set the container hidden to avoid a flash of unstyled content
when the page first loads -->
<div id="notification" style="display:none">
    <!--
    Later on, you can choose which template to use by referring to the
    ID assigned to each template.  Alternatively, you could refer
    to each template by index, so in this example, "basic-tempate" is
    index 0 and "advanced-template" is index 1.
    -->
    <div id="basic-template">
        <a class="ui-notify-cross ui-notify-close" href="#">x</a>
        <h1>#{title}</h1>
        <p>#{text}</p>
    </div>

    <div id="advanced-template">
        <a class="ui-notify-cross ui-notify-close" href="#">x</a>
        <h1>#{title}</h1>
        <p>#{text}</p>
    </div>
</div>



</body>
</html>