<?php
$form = $this->productform;
//echo $this->formCollection($form); exit;
$title = "Add/Edit Product";
echo $this->form()->openTag($form);
$this->headTitle($title);
?>
<h4>Product<span style="float:right;">
        <?php echo $this->formRow($form->get('submit')->setAttribute("class", "btn btn-primary")); ?>
        <a class="btn btn-default" href="<?php echo $this->url("admin-product"); ?>">Cancel</a></span></h4>
<hr>

<?php
echo $this->formHidden($form->get('product_id'));
echo $this->formRow($form->get('title'), null, false);
if ($this->formElementerrors($form->get('title'))) {
    echo '<div class="alert alert-danger" role="alert">' . $this->formElementerrors($form->get('title')) . '</div>';
}
echo $this->formRow($form->get('barcode'), null, false);
if ($this->formElementerrors($form->get('barcode'))) {
    echo '<div class="alert alert-danger" role="alert">' . $this->formElementerrors($form->get('barcode')) . '</div>';
}

echo $this->formRow($form->get('price'), null, false);
if ($this->formElementerrors($form->get('price'))) {
    echo '<div class="alert alert-danger" role="alert">' . $this->formElementerrors($form->get('price')) . '</div>';
}
?>



Select Product Option Group<br>
<script>var options = [];</script>
<select id="product_options" name="product_options">
    <option selected disabled>Select Product Option Group</option>
<?php

$start = "";
$last = 0;
foreach ($this->options as $i => $option){
    if($start != $option->getName()){
        //new option
        ?>
<script>
    options[<?php echo $last; ?>] = [];
    options[<?php echo $last; ?>].push('<?php echo $option->getOptionName()?>');
</script>
<?php
        $last += 1;
        $start = $option->getName();

        echo '<option value="'.($last-1).'">'.$option->getName().'</option>';


    }
    else{
        //old option
        ?>
<script>
        options[<?php echo $last-1; ?>].push('<?php echo $option->getOptionName()?>');
</script>
<?php
    }
}
?>
</select>
<script>
    $(document).ready(function () {
        $("#product_options").change(function () {
            var val = parseInt($(this).val());

            $(".custom-title").each(function(){
                $(this).parent().parent().prev().remove();
                $(this).parent().parent().remove();
            });
            var ref = $(this);

            var option = options[val];
            var html = '';
            for(var i = 0; i < option.length ; ++i){
                html += '<div class="row"><div class="col-xs-6"><div class="row label-txt">Product Option</div></div><div class="col-xs-6"><div class="row label-txt">Product Option Quantity (Use qty -1 for unlimited)</div></div></div>';

                html += '<div class="row">'+
                    '<div class="col-xs-6">'+
                    '<input type="text" class="form-control custom-title" name="option_title[]" value="'+option[i]+'" readonly>'+
                    '</div>'+
                    ' <div class="col-xs-6">'+
                    ''+
                    '<input type="text" value="" class="form-control" placeholder="Available Quantity" name="available_qty[]">'+
                    ''+
                    ''+
                    ''+
                    '</div>'+
                    '</div>';
            }
            ref.after(html);
        });
    });
</script>

<?php
if ($this->productOptions && $this->productOptions->count() >= 1) {
    foreach ($this->productOptions as $number => $row) {
        $title = explode(" || ", $row->option_title);
        if( count($title) == 2 ){
            $row->option_title = $title[1];
            ?>
            <script>
                $("#product_options option:contains('<?php echo $title[0]; ?>')").attr("selected", 'selected');
            </script>
            <?php
        }
        ?>
        <div class="row">
            <div class="col-xs-6">
                <div class="row label-txt">Product Option</div>
            </div>
            <div class="col-xs-6">
                <div class="row label-txt">Product Option Quantity (Use qty -1 for unlimited)</div>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-6">

                <?php
                echo $this->formRow($form->get('option_title[]')->setAttribute("value", $row->option_title), null, false);
                if ($this->formElementerrors($form->get('option_title[]'))) {
                    echo '<div class="alert alert-danger" role="alert">' . $this->formElementerrors($form->get('option_title[]')) . '</div>';
                }
                ?>

            </div>
            <div class="col-xs-6">


                    <?php
                    echo $this->formRow($form->get('available_qty[]')->setAttribute("value", $row->available_qty), null, false);
                    if ($this->formElementerrors($form->get('available_qty[]'))) {
                        echo '
<div class="alert alert-danger" role="alert">' . $this->formElementerrors($form->get('available_qty[]')) . '</div>';
                    }
                    ?>



            </div>
        </div>
    <?php
    }
} else {
    ?>

    <div class="row">
        <div class="col-xs-6">
            <?php
            echo $this->formRow($form->get('option_title[]'), null, false);
            if ($this->formElementerrors($form->get('option_title[]'))) {
                echo '<div class="alert alert-danger" role="alert">' . $this->formElementerrors($form->get('option_title[]')) . '</div>';
            }
            ?>

        </div>
        <div class="col-xs-6">

                <?php
                echo $this->formRow($form->get('available_qty[]'), null, false);
                if ($this->formElementerrors($form->get('available_qty[]'))) {
                    echo '
<div class="alert alert-danger" role="alert">' . $this->formElementerrors($form->get('available_qty[]')) . '</div>';
                }
                ?>


        </div>
    </div>
<?php
}
echo $this->formRow($form->get('description'), null, false);
if ($this->formElementerrors($form->get('description'))) {
    echo '<div class="alert alert-danger" role="alert">' . $this->formElementerrors($form->get('description')) . '</div>';
}
echo $this->formRow($form->get('meta_title'), null, false);
if ($this->formElementerrors($form->get('meta_title'))) {
    echo '
<div class="alert alert-danger" role="alert">' . $this->formElementerrors($form->get('meta_title')) . '</div>';
}
echo $this->formRow($form->get('meta_description'), null, false);
if ($this->formElementerrors($form->get('meta_description'))) {
    echo '
<div class="alert alert-danger" role="alert">' . $this->formElementerrors($form->get('meta_description')) . '</div>';
}
echo $this->formRow($form->get('meta_keyword'), null, false);
if ($this->formElementerrors($form->get('meta_keyword'))) {
    echo '
<div class="alert alert-danger" role="alert">' . $this->formElementerrors($form->get('meta_keyword')) . '</div>';
}
echo $this->formRow($form->get('sort_order'), null, false);
if ($this->formElementerrors($form->get('sort_order'))) {
    echo '
<div class="alert alert-danger" role="alert">' . $this->formElementerrors($form->get('sort_order')) . '</div>';
}
echo $this->formRow($form->get('category_id'), null, false);
if ($this->formElementerrors($form->get('category_id'))) {
    echo '
<div class="alert alert-danger" role="alert">' . $this->formElementerrors($form->get('category_id')) . '</div>';
}

?>

<h5>Product Images</h5>
<hr>
<div class="input-group">
    <?php
    echo $this->formRow($form->get('main_image'), null, false);

    ?>
    <span class="input-group-btn">
<a href="<?php echo $this->url("home"); ?>ResponsiveFilemanager/filemanager/dialog.php?type=1&field_id=main_image" class="btn btn-default select_image">Select</a>
</span>
</div>
<?php
if($this->formElementerrors($form->get('main_image'))){
    echo '<div class="alert alert-danger" role="alert">'.$this->formElementerrors($form->get('main_image')).'</div>';
}

?>
<div class='row thumb-container'>
    <?php if($form->get('main_image')->getValue()){ ?>
    <div class='col-xs-2'>
        <img src="<?php echo $form->get('main_image')->getValue(); ?>" style="width:50px; height:auto;" />
        </div>
    <?php } ?>
</div>
<div class="input-group">
    <?php
    //if(!$this->productImages){
        echo $this->formRow($form->get('image[]'), null, false);
    //}
    ?>
    <span class="input-group-btn">
<a href="<?php echo $this->url("home"); ?>ResponsiveFilemanager/filemanager/dialog.php?type=1&field_id=image" id="add_more_image_btn" class="btn btn-default select_image">Add More Images</a>
</span>
</div>
<div class='row thumb-container'>
    <?php if($this->productImages){
        foreach($this->productImages as $k=> $image){
        ?>
        <div class='col-xs-2'>
            <img src="<?php echo $this->url("home").$this->settingHelper("thumbs_dir")."/". $image->image; ?>" class="img_href"/><br>
            <?php  if($k == 0) { ?>
                [ <a href='javascript:;' onclick='removeImage(this);' class="image">Remove</a> ]
                <input type="hidden" name="image[]" id="image_<?php echo $k; ?>" value="<?php echo $image->image; ?>" class="more_images"/>

            <?php } else {?>
                [ <a href='javascript:;' onclick='removeImage(this);' class="image_<?php echo $k; ?>">Remove</a> ]
                <input type="hidden" name="image[]" id="image_<?php echo $k; ?>" value="<?php echo $image->image; ?>" class="more_images"/>
                <?php } ?>
        </div>
    <?php } } ?>
</div>

<?php



echo $this->formRow($form->get('enabled'), null, false);
if ($this->formElementerrors($form->get('enabled'))) {
    echo '
<div class="alert alert-danger" role="alert">' . $this->formElementerrors($form->get('enabled')) . '</div>';
}
echo $this->form()->closeTag();
?>
<style>
    #productform label span, #productform > input {
        display: block;

    }

    #productform > label {
        width: 100%;
        font-weight: normal;
    }

    #productform > label > input {
        width: 100%;
    }

    #productform > label > input[type=radio] {
        width: auto;
        display: inline;
    }

    textarea {
        width: 100%;
    }

    .label-txt {
        padding: 0px 15px ;
    }
    .thumb-container{
        padding: 10px;
    }

</style>
<?php
$this->headLink()->prependStylesheet($this->basePath() . '/js/fancybox/source/jquery.fancybox.css')
?>
<?php $this->headScript()
    ->prependFile($this->basePath() . '/js/tinymce/tinymce.min.js')
    ->prependFile($this->basePath() . '/js/fancybox/source/jquery.fancybox.js'); ?>

<script type="text/javascript">
    $(document).ready(function () {
        $('.select_image').fancybox({
            'width': 880,
            'height': 570,
            'type': 'iframe',
            'autoScale': true
        });
        tinymce.init({
            selector: "#description",
            theme: "modern",
            plugins: [
                "advlist autolink link image lists charmap print preview hr anchor pagebreak",
                "searchreplace wordcount visualblocks visualchars insertdatetime media code nonbreaking",
                "table contextmenu directionality emoticons paste textcolor responsivefilemanager"
            ],
            toolbar1: "undo redo | bold italic underline | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | styleselect",
            toolbar2: "| responsivefilemanager | link unlink anchor | image media | forecolor backcolor  | print preview code ",
            image_advtab: true,

            external_filemanager_path: "<?php echo $this->url("home"); ?>ResponsiveFilemanager/filemanager/",
            filemanager_title: "File Manager",
            external_plugins: { "filemanager": "<?php echo $this->url("home"); ?>ResponsiveFilemanager/filemanager/plugin.min.js"}
        });


        var optionHtml = '<div class="row label-txt"><div class="col-xs-6">' +
            '<input class="form-control" type="text" value="default" placeholder="Option Title" name="option_title[]">' +
            '</div>' +
            '<div class="col-xs-6">' +
            '<div class="input-group half-container">' +
            '<input class="form-control" type="text" value="" placeholder="Available Quantity" name="available_qty[]">' +
            '<span class="input-group-btn">' +
            '<button class="btn btn-default plus" type="button">+</button>' +
            '</span>' +
            '</div>' +
            '</div></div>';
        $('.plus').click(function () {
            $(this).parent().parent().parent().parent().append(optionHtml);
            $('.plus').each(function(i){
                if(i != 0){
                    $(this).addClass("minus");
                    $(this).html("-");
                    $(this).removeClass("plus");
                }
            });
            $('.minus').click(function () {
                $(this).parent().parent().parent().parent().remove();
            });
        });
        $('.minus').click(function () {
            $(this).parent().parent().parent().parent().remove();
        });

        $('form').eq(0).submit(function(){
            removeErrors();
            var is_valid = true;
            var elements = [
                $("input[name=title]"),
                $("input[name=barcode]"),
                $("input[name=sort_order]"),
                $("input[name=price]"),
                $("input[name='available_qty[]']")
            ];
            $(elements).each(function(){
                if( $(this).val().replace(/ /g,'') == ""){
                    showError('empty', this);
                    is_valid = false;
                }

            });

            var price = $("input[name=price]").val();
            if(isNaN(price)){
                showError("float", $("input[name=price]").get());
                is_valid = false;
            }

            var main_image = $("input[name=main_image]").val();
            if(main_image.length == 0){
                alert('Product Image is required.');
                $("input[name=main_image]").focus();
                is_valid = false;
            }


            var qty  = $("input[name='available_qty[]']").val();

            if(isNaN(qty)){
                showError("int", $("input[name='available_qty[]']").get());
                is_valid = false;
            }

            var sort = $("input[name=sort_order]").val();
            if(isNaN(sort)){
                showError("int", $("input[name=sort_order]").get());
                is_valid = false;
            }
            if(is_valid){
                $("#product_options option:selected").val($("#product_options option:selected").html());
            }
            return is_valid;
        });

        $("form").eq(0).submit(function(){

            $(".more_images").remove();
            $(".img_href").each(function(){
                var url = $(this).attr("src").replace("thumbs", "source");

                $("form").eq(0).append("<input type='hidden' name='image[]' value='"+url+"' />");
            });
        });


    });
function handleImage(_obj){

    var img_url = $(_obj).val().replace("ResponsiveFilemanager/source/", "ResponsiveFilemanager/thumbs/");

    if($(_obj).attr("name") == "main_image"){
        var html = "<div class='col-xs-2'>"+
            "<img src='"+img_url+"' />"+
            "</div>";
        $(".thumb-container").eq(0).html(html);
    }
    else{

        var more_image_id = "image_"+$(".more_images").length;
        var html = "<div class='col-xs-2'>"+
            "<img src='"+img_url+"' class='img_href'/><br>"+

            "[ <a href='javascript:;' onclick='removeImage(this);' class="+more_image_id+">Remove</a> ] " +
            '<input type="hidden" onchange="handleImage(this);" class="more_images" id="'+more_image_id+'" name="image[]">'+
            "</div>";
        $(".thumb-container").eq(1).append(html);


        //$(".thumb-container").eq(1).append(more_image);
        var new_url = '<?php echo $this->url("home"); ?>ResponsiveFilemanager/filemanager/dialog.php?type=1&field_id='+more_image_id;
        $("#add_more_image_btn").attr("href", new_url);
        $(".more_images").eq(0).val("");
    }

}
    function removeImage(_obj){
        var image_class = $(_obj).attr("class");
        $(_obj).parent().remove();
        $("#"+image_class).val("");
    }

</script>
