<?php
use Zend\Form\Form;
$form = new Form();
$form->setAttribute("action" , $this->url());
$form->setAttribute("method" , 'post');
$form->prepare();
echo $this->form()->openTag($form);
$this->headTitle("Categories");
?>
<h4>Categories <span style="float:right;"><a href="<?php echo $this->url("admin-category", array('action'=>'add')); ?>" class="btn btn-default">Add</a> <input type="submit" class="btn btn-danger" value="Delete" /></span></h4>
<hr>
<?php if ($this->success_add){ ?>
    <div class="alert alert-success" role="alert">
        <?php echo $this->success_add; ?>
    </div>
<?php } ?>
<table class="table table-hover">

    <thead>

    <tr>
        <th><input type="checkbox" name="allCategories" value="all"/></th>
        <th>ID</th>

        <th>Category Name</th>

        <th>Sort Order</th>

        <th>Enabled</th>

        <th>Action</th>
    </tr>
    </thead>

    <tbody>
<?php
foreach ($this->categories as $category) {

    ?>
    <tr>
        <td><input type="checkbox" name="categories[]" value="<?php echo $category->getId(); ?>"/></td>
            <td><?php echo $category->getId(); ?></td>

            <td>
                <?php
                $name = $category->getTitle();
                $temp = $category;
                while($temp->getParentCategoryId() != 0){
                    $temp = $this->category_table->getCategory((int)$temp->getParentCategoryId());
                    $name_with_parent = $temp->getTitle() . " > " . $name;
                    $name = $name_with_parent;
                }
                echo $name;
                ?>
            </td>

            <td><?php echo $category->getSortOrder(); ?></td>
            <td><?php echo $category->getEnabled() == 1 ? "Yes" : "No"; ?></td>
            <td><a href="<?php echo $this->url("admin-category-edit", array("id" => $category->getId())); ?>" class="btn btn-default">Edit</a></td>

        </tr>
    <?php
}
?>
    </tbody>
    </table>
<?php
    echo $this->form()->closeTag();

?>
<?php // add at the end of the file after the table
echo $this->paginationControl(
// the paginator object
    $this->categories,
    // the scrolling style; see http://zf2.readthedocs.org/en/release-2.1.4/modules/zend.paginator.usage.html#rendering-pages-with-view-scripts
    'sliding',
    // the partial to use to render the control
    array('partial/paginator.phtml', 'Category'),
    // the route to link to when a user clicks a control link
    array(
        'route' => 'admin-category'
    )
);
?>

<script>
    jQuery(document).ready(function($){
        $("input[name=allCategories]").change(function(){

            if($(this).is(":checked")){
                $("input[type=checkbox]").prop('checked',true);

            }
            else{
                $("input[type=checkbox]").prop('checked',false);

            }
        });
        $('form').submit(function(){
            if(!window.confirm("In selected category/categories, all products categories will be set to null.\nAll of child categories will become root categories.\nAre you sure?")){
                return false;
            }
        });
    });
</script>